/**
 * ReachVet - HTML Report Generator
 * 
 * Generates standalone HTML reports with charts and interactive filtering.
 */

import type { AnalysisOutput, ComponentResult, AnalysisSummary, ReachabilityStatus } from '../types.js';

// ============================================================
// Options
// ============================================================

export interface HtmlOptions {
  /** Report title */
  title?: string;
  /** Include interactive features (search/filter) */
  interactive?: boolean;
  /** Include pie chart */
  includeChart?: boolean;
  /** Dark mode */
  darkMode?: boolean;
}

// ============================================================
// Status Colors
// ============================================================

const STATUS_COLORS: Record<ReachabilityStatus, { bg: string; text: string; label: string }> = {
  reachable: { bg: '#22c55e', text: '#ffffff', label: 'Reachable' },
  imported: { bg: '#eab308', text: '#000000', label: 'Imported' },
  not_reachable: { bg: '#94a3b8', text: '#000000', label: 'Not Reachable' },
  indirect: { bg: '#3b82f6', text: '#ffffff', label: 'Indirect' },
  unknown: { bg: '#6b7280', text: '#ffffff', label: 'Unknown' },
};

// ============================================================
// Generator
// ============================================================

/**
 * Generate standalone HTML report
 */
export function toHtml(output: AnalysisOutput, options: HtmlOptions = {}): string {
  const { title = 'ReachVet Analysis Report', interactive = true, includeChart = true, darkMode = false } = options;

  const jsonData = JSON.stringify(output, null, 2);

  return `<!DOCTYPE html>
<html lang="en" ${darkMode ? 'class="dark"' : ''}>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
${generateStyles(darkMode)}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>📊 ${escapeHtml(title)}</h1>
      <div class="meta">
        <span>Generated: ${output.timestamp}</span>
        <span>Language: ${output.language}</span>
        <span>Source: <code>${escapeHtml(output.sourceDir)}</code></span>
      </div>
    </header>

    ${generateSummarySection(output.summary, includeChart)}
    
    ${output.summary.vulnerableReachable > 0 ? generateVulnerabilitySection(output.results) : ''}
    
    ${generateDetailsSection(output.results, interactive)}
    
    ${output.summary.warningsCount > 0 ? generateWarningsSection(output.results) : ''}
    
    <footer>
      <p>Generated by ReachVet v${output.version}</p>
    </footer>
  </div>

  ${interactive ? generateScript(jsonData) : ''}
</body>
</html>`;
}

/**
 * Generate CSS styles
 */
function generateStyles(darkMode: boolean): string {
  const bg = darkMode ? '#1a1a2e' : '#f8fafc';
  const cardBg = darkMode ? '#16213e' : '#ffffff';
  const text = darkMode ? '#e2e8f0' : '#1e293b';
  const textMuted = darkMode ? '#94a3b8' : '#64748b';
  const border = darkMode ? '#374151' : '#e2e8f0';

  return `
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: ${bg};
      color: ${text};
      line-height: 1.6;
      padding: 2rem;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    header { margin-bottom: 2rem; }
    header h1 { font-size: 1.75rem; margin-bottom: 0.5rem; }
    .meta { display: flex; gap: 1.5rem; color: ${textMuted}; font-size: 0.875rem; flex-wrap: wrap; }
    .meta code { background: ${darkMode ? '#374151' : '#e2e8f0'}; padding: 0.125rem 0.375rem; border-radius: 4px; }
    
    .card {
      background: ${cardBg};
      border-radius: 12px;
      padding: 1.5rem;
      margin-bottom: 1.5rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      border: 1px solid ${border};
    }
    .card h2 { font-size: 1.25rem; margin-bottom: 1rem; display: flex; align-items: center; gap: 0.5rem; }
    
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 1rem;
    }
    .stat-card {
      text-align: center;
      padding: 1rem;
      border-radius: 8px;
      background: ${darkMode ? '#1a1a2e' : '#f1f5f9'};
    }
    .stat-value { font-size: 2rem; font-weight: bold; }
    .stat-label { font-size: 0.875rem; color: ${textMuted}; }
    
    .chart-container {
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 1rem;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.875rem;
    }
    th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid ${border}; }
    th { background: ${darkMode ? '#1a1a2e' : '#f1f5f9'}; font-weight: 600; position: sticky; top: 0; }
    tr:hover { background: ${darkMode ? '#1a1a2e' : '#f8fafc'}; }
    
    .badge {
      display: inline-block;
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 500;
    }
    .badge-reachable { background: #22c55e; color: white; }
    .badge-imported { background: #eab308; color: black; }
    .badge-not_reachable { background: #94a3b8; color: black; }
    .badge-indirect { background: #3b82f6; color: white; }
    .badge-unknown { background: #6b7280; color: white; }
    
    .severity-critical { color: #dc2626; font-weight: bold; }
    .severity-high { color: #f97316; font-weight: bold; }
    .severity-medium { color: #eab308; }
    .severity-low { color: #22c55e; }
    
    .vuln-id { font-family: monospace; background: ${darkMode ? '#374151' : '#fee2e2'}; padding: 0.125rem 0.375rem; border-radius: 4px; }
    
    .search-box {
      display: flex;
      gap: 1rem;
      margin-bottom: 1rem;
      flex-wrap: wrap;
    }
    .search-box input, .search-box select {
      padding: 0.5rem 1rem;
      border: 1px solid ${border};
      border-radius: 6px;
      background: ${cardBg};
      color: ${text};
      font-size: 0.875rem;
    }
    .search-box input { flex: 1; min-width: 200px; }
    
    .table-container { overflow-x: auto; max-height: 600px; overflow-y: auto; }
    
    .warning-item {
      padding: 0.75rem;
      background: ${darkMode ? '#2d1f1f' : '#fef3c7'};
      border-left: 4px solid #eab308;
      margin-bottom: 0.5rem;
      border-radius: 0 8px 8px 0;
    }
    .warning-code { font-family: monospace; font-weight: 600; }
    .warning-location { color: ${textMuted}; font-size: 0.75rem; }
    
    footer { margin-top: 2rem; text-align: center; color: ${textMuted}; font-size: 0.875rem; }
    
    .hidden { display: none; }
    
    @media (max-width: 768px) {
      body { padding: 1rem; }
      .meta { flex-direction: column; gap: 0.5rem; }
    }
  `;
}

/**
 * Generate summary section
 */
function generateSummarySection(summary: AnalysisSummary, includeChart: boolean): string {
  const chartHtml = includeChart
    ? `
    <div class="chart-container">
      <svg viewBox="0 0 200 200" width="180" height="180">
        ${generatePieChart(summary)}
      </svg>
    </div>`
    : '';

  return `
    <section class="card">
      <h2>📊 Summary</h2>
      <div class="summary-grid">
        <div class="stat-card">
          <div class="stat-value">${summary.total}</div>
          <div class="stat-label">Total Dependencies</div>
        </div>
        <div class="stat-card">
          <div class="stat-value" style="color: #22c55e">${summary.reachable}</div>
          <div class="stat-label">Reachable</div>
        </div>
        <div class="stat-card">
          <div class="stat-value" style="color: #eab308">${summary.imported}</div>
          <div class="stat-label">Imported</div>
        </div>
        <div class="stat-card">
          <div class="stat-value" style="color: #94a3b8">${summary.notReachable}</div>
          <div class="stat-label">Not Reachable</div>
        </div>
        <div class="stat-card">
          <div class="stat-value" style="color: ${summary.vulnerableReachable > 0 ? '#dc2626' : '#22c55e'}">${summary.vulnerableReachable}</div>
          <div class="stat-label">Vulnerable & Reachable</div>
        </div>
      </div>
      ${chartHtml}
    </section>`;
}

/**
 * Generate SVG pie chart
 */
function generatePieChart(summary: AnalysisSummary): string {
  const data = [
    { value: summary.reachable, color: STATUS_COLORS.reachable.bg, label: 'Reachable' },
    { value: summary.imported, color: STATUS_COLORS.imported.bg, label: 'Imported' },
    { value: summary.notReachable, color: STATUS_COLORS.not_reachable.bg, label: 'Not Reachable' },
    { value: summary.indirect, color: STATUS_COLORS.indirect.bg, label: 'Indirect' },
    { value: summary.unknown, color: STATUS_COLORS.unknown.bg, label: 'Unknown' },
  ].filter((d) => d.value > 0);

  if (data.length === 0 || summary.total === 0) {
    return '<text x="100" y="100" text-anchor="middle">No data</text>';
  }

  const total = data.reduce((sum, d) => sum + d.value, 0);
  let currentAngle = -90;

  const paths = data.map((d) => {
    const angle = (d.value / total) * 360;
    const startAngle = currentAngle;
    const endAngle = currentAngle + angle;
    currentAngle = endAngle;

    const startRad = (startAngle * Math.PI) / 180;
    const endRad = (endAngle * Math.PI) / 180;
    const largeArc = angle > 180 ? 1 : 0;

    const x1 = 100 + 80 * Math.cos(startRad);
    const y1 = 100 + 80 * Math.sin(startRad);
    const x2 = 100 + 80 * Math.cos(endRad);
    const y2 = 100 + 80 * Math.sin(endRad);

    return `<path d="M100,100 L${x1},${y1} A80,80 0 ${largeArc},1 ${x2},${y2} Z" fill="${d.color}" stroke="white" stroke-width="2">
      <title>${d.label}: ${d.value} (${((d.value / total) * 100).toFixed(1)}%)</title>
    </path>`;
  });

  return paths.join('\n        ');
}

/**
 * Generate vulnerability section
 */
function generateVulnerabilitySection(results: ComponentResult[]): string {
  const vulnerable = results.filter(
    (r) =>
      (r.status === 'reachable' || r.status === 'imported') &&
      r.component.vulnerabilities &&
      r.component.vulnerabilities.length > 0
  );

  const rows = vulnerable
    .map((r) => {
      const vulns = r.component.vulnerabilities!;
      const vulnHtml = vulns
        .map((v) => `<span class="vuln-id">${escapeHtml(v.id)}</span>`)
        .join(' ');
      const maxSeverity = getMaxSeverity(vulns.map((v) => v.severity || 'unknown'));

      return `
        <tr>
          <td><strong>${escapeHtml(r.component.name)}</strong></td>
          <td>${escapeHtml(r.component.version)}</td>
          <td><span class="badge badge-${r.status}">${r.status}</span></td>
          <td>${vulnHtml}</td>
          <td class="severity-${maxSeverity}">${maxSeverity.toUpperCase()}</td>
        </tr>`;
    })
    .join('');

  return `
    <section class="card">
      <h2>⚠️ Vulnerable Dependencies</h2>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>Component</th>
              <th>Version</th>
              <th>Status</th>
              <th>Vulnerabilities</th>
              <th>Severity</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>
    </section>`;
}

/**
 * Generate details section
 */
function generateDetailsSection(results: ComponentResult[], interactive: boolean): string {
  const searchHtml = interactive
    ? `
      <div class="search-box">
        <input type="text" id="searchInput" placeholder="Search components..." onkeyup="filterTable()">
        <select id="statusFilter" onchange="filterTable()">
          <option value="">All Statuses</option>
          <option value="reachable">Reachable</option>
          <option value="imported">Imported</option>
          <option value="not_reachable">Not Reachable</option>
          <option value="indirect">Indirect</option>
          <option value="unknown">Unknown</option>
        </select>
      </div>`
    : '';

  const rows = results
    .map((r) => {
      const usedMembers = r.usage?.usedMembers?.slice(0, 5).join(', ') || '-';
      const locations =
        r.usage?.locations
          ?.slice(0, 2)
          .map((l) => `${escapeHtml(l.file)}:${l.line}`)
          .join(', ') || '-';
      const vulnCount = r.component.vulnerabilities?.length || 0;

      return `
        <tr data-status="${r.status}" data-name="${escapeHtml(r.component.name.toLowerCase())}">
          <td><strong>${escapeHtml(r.component.name)}</strong></td>
          <td>${escapeHtml(r.component.version)}</td>
          <td><span class="badge badge-${r.status}">${r.status}</span></td>
          <td>${usedMembers}</td>
          <td><code>${locations}</code></td>
          <td>${vulnCount > 0 ? `<span class="severity-high">${vulnCount}</span>` : '-'}</td>
        </tr>`;
    })
    .join('');

  return `
    <section class="card">
      <h2>📋 All Components</h2>
      ${searchHtml}
      <div class="table-container">
        <table id="componentsTable">
          <thead>
            <tr>
              <th>Component</th>
              <th>Version</th>
              <th>Status</th>
              <th>Used Members</th>
              <th>Locations</th>
              <th>Vulns</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>
    </section>`;
}

/**
 * Generate warnings section
 */
function generateWarningsSection(results: ComponentResult[]): string {
  const warnings: string[] = [];

  for (const r of results) {
    if (r.warnings) {
      for (const w of r.warnings) {
        warnings.push(`
          <div class="warning-item">
            <span class="warning-code">${escapeHtml(w.code)}</span>: 
            ${escapeHtml(r.component.name)} - ${escapeHtml(w.message)}
            ${w.location ? `<div class="warning-location">${escapeHtml(w.location.file)}:${w.location.line}</div>` : ''}
          </div>`);
      }
    }
  }

  return `
    <section class="card">
      <h2>⚠️ Analysis Warnings (${warnings.length})</h2>
      ${warnings.slice(0, 50).join('')}
      ${warnings.length > 50 ? `<p><em>...and ${warnings.length - 50} more warnings</em></p>` : ''}
    </section>`;
}

/**
 * Generate interactive script
 */
function generateScript(jsonData: string): string {
  return `
  <script>
    const analysisData = ${jsonData};
    
    function filterTable() {
      const search = document.getElementById('searchInput').value.toLowerCase();
      const status = document.getElementById('statusFilter').value;
      const rows = document.querySelectorAll('#componentsTable tbody tr');
      
      rows.forEach(row => {
        const name = row.getAttribute('data-name');
        const rowStatus = row.getAttribute('data-status');
        const matchesSearch = !search || name.includes(search);
        const matchesStatus = !status || rowStatus === status;
        row.classList.toggle('hidden', !(matchesSearch && matchesStatus));
      });
    }
  </script>`;
}

/**
 * Escape HTML entities
 */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Get maximum severity
 */
function getMaxSeverity(severities: string[]): string {
  const order = ['critical', 'high', 'medium', 'low', 'unknown'];
  for (const level of order) {
    if (severities.includes(level)) {
      return level;
    }
  }
  return 'unknown';
}
