/**
 * Shell Completions Generator
 *
 * Generates shell completion scripts for bash, zsh, and fish.
 */

import { VERSION } from '../version.js';

/** Supported shell types */
export type ShellType = 'bash' | 'zsh' | 'fish';

/** All ReachVet commands */
const COMMANDS = [
  'analyze',
  'check',
  'languages',
  'detect',
  'osv-lookup',
  'osv-cache',
  'watch',
  'pre-commit',
  'pre-commit-config',
  'init',
  'config',
  'serve',
  'completions',
] as const;

/** Command descriptions */
const COMMAND_DESCRIPTIONS: Record<string, string> = {
  analyze: 'Analyze if components are reachable in source code',
  check: 'Check reachability with human-readable output',
  languages: 'List supported languages',
  detect: 'Auto-detect language from source directory',
  'osv-lookup': 'Look up vulnerabilities from OSV.dev',
  'osv-cache': 'Manage OSV cache',
  watch: 'Watch source files and re-analyze on changes',
  'pre-commit': 'Run reachability check as a pre-commit hook',
  'pre-commit-config': 'Generate .pre-commit-hooks.yaml configuration',
  init: 'Create a configuration file in the current directory',
  config: 'Show current configuration',
  serve: 'Start ReachVet API server',
  completions: 'Generate shell completion script',
};

/** Supported languages for --language option */
const LANGUAGES = [
  'javascript',
  'typescript',
  'python',
  'go',
  'java',
  'rust',
  'ruby',
  'php',
  'csharp',
  'swift',
  'kotlin',
  'scala',
  'elixir',
  'dart',
  'perl',
  'haskell',
  'clojure',
  'ocaml',
] as const;

/** Options for analyze/check commands */
const ANALYZE_OPTIONS = [
  '-s|--source',
  '-c|--components',
  '--sbom',
  '--stdin',
  '-l|--language',
  '-v|--verbose',
  '--pretty',
  '--sarif',
  '--graph',
  '--dot',
  '--graph-direction',
  '--vulnerable-only',
  '--osv',
  '--osv-cache',
  '--osv-ttl',
  '--junit',
  '--junit-all',
  '--annotations',
  '--annotations-notices',
  '--sbom-cyclonedx',
  '--sbom-spdx',
  '--sbom-include-unreachable',
  '--vex',
  '--app-name',
  '--app-version',
];

/** Options for watch command */
const WATCH_OPTIONS = [
  '-s|--source',
  '-c|--components',
  '--sbom',
  '-l|--language',
  '--osv',
  '--osv-cache',
  '--osv-ttl',
  '--debounce',
  '--quiet',
  '--ignore',
];

/** Options for serve command */
const SERVE_OPTIONS = [
  '-p|--port',
  '-H|--host',
  '--cors',
  '--no-cors',
  '--api-key',
  '--rate-limit',
  '--no-rate-limit',
  '--osv-cache',
  '--no-osv-cache',
  '--cache-ttl',
];

/** Options for pre-commit command */
const PRECOMMIT_OPTIONS = [
  '-c|--components',
  '--sbom',
  '-l|--language',
  '--osv',
  '--osv-cache',
  '--osv-ttl',
  '--verbose',
  '--no-color',
  '--block-on-reachable',
  '--skip-no-staged',
];

/** Options for osv-lookup command */
const OSV_LOOKUP_OPTIONS = [
  '-p|--package',
  '-v|--version',
  '-e|--ecosystem',
  '--functions',
  '--pretty',
];

/** Options for osv-cache command */
const OSV_CACHE_OPTIONS = [
  '--stats',
  '--clear',
  '--dir',
];

/** Options for init command */
const INIT_OPTIONS = [
  '-f|--format',
  '--force',
];

/** Options for config command */
const CONFIG_OPTIONS = [
  '-c|--config',
  '--validate',
];

/**
 * Generate Bash completion script
 */
export function generateBashCompletions(): string {
  const cmdList = COMMANDS.join(' ');
  const langList = LANGUAGES.join(' ');

  return `# Bash completion for reachvet
# Generated by ReachVet v${VERSION}
# 
# Installation:
#   # For current session:
#   source <(reachvet completions bash)
#
#   # Permanent (add to ~/.bashrc):
#   reachvet completions bash >> ~/.bashrc
#
#   # Or save to completions directory:
#   reachvet completions bash > /etc/bash_completion.d/reachvet
#   # or for user:
#   reachvet completions bash > ~/.local/share/bash-completion/completions/reachvet

_reachvet_completions() {
    local cur prev words cword
    _init_completion || return

    local commands="${cmdList}"
    local languages="${langList}"

    # Handle --language option completion
    if [[ "\${prev}" == "-l" || "\${prev}" == "--language" ]]; then
        COMPREPLY=( $(compgen -W "\${languages}" -- "\${cur}") )
        return 0
    fi

    # Handle --format option for init command
    if [[ "\${prev}" == "-f" || "\${prev}" == "--format" ]]; then
        COMPREPLY=( $(compgen -W "json js" -- "\${cur}") )
        return 0
    fi

    # Handle --graph-direction option
    if [[ "\${prev}" == "--graph-direction" ]]; then
        COMPREPLY=( $(compgen -W "TB LR BT RL" -- "\${cur}") )
        return 0
    fi

    # Handle --ecosystem option for osv-lookup
    if [[ "\${prev}" == "-e" || "\${prev}" == "--ecosystem" ]]; then
        COMPREPLY=( $(compgen -W "npm pypi go maven cargo crates.io nuget rubygems packagist" -- "\${cur}") )
        return 0
    fi

    # Handle file/directory options
    case "\${prev}" in
        -s|--source|-c|--components|--sbom|--osv-cache|--dir|--config)
            _filedir
            return 0
            ;;
        --graph|--dot|--junit|--sbom-cyclonedx|--sbom-spdx|--vex|-o|--output)
            _filedir
            return 0
            ;;
    esac

    # First argument - complete commands
    if [[ \${cword} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
        return 0
    fi

    # Command-specific completions
    local cmd="\${words[1]}"
    case "\${cmd}" in
        analyze|check)
            local opts="${ANALYZE_OPTIONS.map(o => o.split('|').pop()).join(' ')}"
            COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
            ;;
        watch)
            local opts="${WATCH_OPTIONS.map(o => o.split('|').pop()).join(' ')}"
            COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
            ;;
        serve)
            local opts="${SERVE_OPTIONS.map(o => o.split('|').pop()).join(' ')}"
            COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
            ;;
        pre-commit)
            local opts="${PRECOMMIT_OPTIONS.map(o => o.split('|').pop()).join(' ')}"
            COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
            ;;
        osv-lookup)
            local opts="${OSV_LOOKUP_OPTIONS.map(o => o.split('|').pop()).join(' ')}"
            COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
            ;;
        osv-cache)
            local opts="${OSV_CACHE_OPTIONS.map(o => o.split('|').pop()).join(' ')}"
            COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
            ;;
        init)
            local opts="${INIT_OPTIONS.map(o => o.split('|').pop()).join(' ')}"
            COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
            ;;
        config)
            local opts="${CONFIG_OPTIONS.map(o => o.split('|').pop()).join(' ')}"
            COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
            ;;
        pre-commit-config)
            COMPREPLY=( $(compgen -W "-o --output" -- "\${cur}") )
            ;;
        completions)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "\${cur}") )
            ;;
        detect)
            _filedir -d
            ;;
        languages)
            # No options
            ;;
    esac

    return 0
}

complete -F _reachvet_completions reachvet
`;
}

/**
 * Generate Zsh completion script
 */
export function generateZshCompletions(): string {
  const cmdDescriptions = COMMANDS.map(cmd =>
    `'${cmd}:${COMMAND_DESCRIPTIONS[cmd] || ''}'`
  ).join('\n            ');

  const langList = LANGUAGES.map(l => `'${l}'`).join(' ');

  return `#compdef reachvet
# Zsh completion for reachvet
# Generated by ReachVet v${VERSION}
#
# Installation:
#   # Save to fpath directory:
#   reachvet completions zsh > ~/.zsh/completions/_reachvet
#
#   # Ensure fpath includes your completions directory:
#   fpath=(~/.zsh/completions $fpath)
#
#   # Rebuild completion cache:
#   rm -f ~/.zcompdump; compinit

_reachvet() {
    local -a commands
    local -a languages
    local -a ecosystems
    local -a graph_directions

    commands=(
            ${cmdDescriptions}
    )

    languages=(${langList})
    ecosystems=('npm' 'pypi' 'go' 'maven' 'cargo' 'crates.io' 'nuget' 'rubygems' 'packagist')
    graph_directions=('TB:Top to Bottom' 'LR:Left to Right' 'BT:Bottom to Top' 'RL:Right to Left')

    _arguments -C \\
        '1: :->command' \\
        '*: :->args'

    case $state in
        command)
            _describe -t commands 'reachvet command' commands
            ;;
        args)
            case $words[2] in
                analyze|check)
                    _arguments \\
                        '-s[Source directory]:directory:_files -/' \\
                        '--source[Source directory]:directory:_files -/' \\
                        '-c[Components JSON file]:file:_files -g "*.json"' \\
                        '--components[Components JSON file]:file:_files -g "*.json"' \\
                        '--sbom[SBOM file]:file:_files -g "*.json"' \\
                        '--stdin[Read from stdin]' \\
                        '-l[Language]:language:($languages)' \\
                        '--language[Language]:language:($languages)' \\
                        '-v[Verbose output]' \\
                        '--verbose[Verbose output]' \\
                        '--pretty[Pretty print JSON]' \\
                        '--sarif[Output SARIF format]' \\
                        '--graph[Output Mermaid graph]:file:_files' \\
                        '--dot[Output DOT graph]:file:_files' \\
                        '--graph-direction[Graph direction]:direction:(($graph_directions))' \\
                        '--vulnerable-only[Only vulnerable in graph]' \\
                        '--osv[Fetch from OSV.dev]' \\
                        '--osv-cache[OSV cache directory]:directory:_files -/' \\
                        '--osv-ttl[OSV cache TTL]:seconds:' \\
                        '--junit[Output JUnit XML]:file:_files -g "*.xml"' \\
                        '--junit-all[Include all in JUnit]' \\
                        '--annotations[GitHub Actions annotations]' \\
                        '--annotations-notices[Include notices]' \\
                        '--sbom-cyclonedx[Output CycloneDX]:file:_files -g "*.json"' \\
                        '--sbom-spdx[Output SPDX]:file:_files -g "*.json"' \\
                        '--sbom-include-unreachable[Include unreachable]' \\
                        '--vex[Output VEX]:file:_files -g "*.json"' \\
                        '--app-name[Application name]:name:' \\
                        '--app-version[Application version]:version:'
                    ;;
                watch)
                    _arguments \\
                        '-s[Source directory]:directory:_files -/' \\
                        '--source[Source directory]:directory:_files -/' \\
                        '-c[Components JSON file]:file:_files -g "*.json"' \\
                        '--components[Components JSON file]:file:_files -g "*.json"' \\
                        '--sbom[SBOM file]:file:_files -g "*.json"' \\
                        '-l[Language]:language:($languages)' \\
                        '--language[Language]:language:($languages)' \\
                        '--osv[Fetch from OSV.dev]' \\
                        '--osv-cache[OSV cache directory]:directory:_files -/' \\
                        '--osv-ttl[OSV cache TTL]:seconds:' \\
                        '--debounce[Debounce ms]:milliseconds:' \\
                        '--quiet[Quiet mode]' \\
                        '*--ignore[Ignore patterns]:pattern:'
                    ;;
                serve)
                    _arguments \\
                        '-p[Port]:port:' \\
                        '--port[Port]:port:' \\
                        '-H[Host]:host:' \\
                        '--host[Host]:host:' \\
                        '--cors[Enable CORS]' \\
                        '--no-cors[Disable CORS]' \\
                        '--api-key[API key]:key:' \\
                        '--rate-limit[Rate limit]:requests:' \\
                        '--no-rate-limit[Disable rate limit]' \\
                        '--osv-cache[Enable OSV cache]' \\
                        '--no-osv-cache[Disable OSV cache]' \\
                        '--cache-ttl[Cache TTL]:milliseconds:'
                    ;;
                pre-commit)
                    _arguments \\
                        '-c[Components JSON file]:file:_files -g "*.json"' \\
                        '--components[Components JSON file]:file:_files -g "*.json"' \\
                        '--sbom[SBOM file]:file:_files -g "*.json"' \\
                        '-l[Language]:language:($languages)' \\
                        '--language[Language]:language:($languages)' \\
                        '--osv[Fetch from OSV.dev]' \\
                        '--osv-cache[OSV cache directory]:directory:_files -/' \\
                        '--osv-ttl[OSV cache TTL]:seconds:' \\
                        '--verbose[Verbose output]' \\
                        '--no-color[Disable colors]' \\
                        '--block-on-reachable[Block on any reachable]' \\
                        '--skip-no-staged[Skip if no staged files]'
                    ;;
                osv-lookup)
                    _arguments \\
                        '-p[Package name]:package:' \\
                        '--package[Package name]:package:' \\
                        '-v[Package version]:version:' \\
                        '--version[Package version]:version:' \\
                        '-e[Ecosystem]:ecosystem:($ecosystems)' \\
                        '--ecosystem[Ecosystem]:ecosystem:($ecosystems)' \\
                        '--functions[Show functions only]' \\
                        '--pretty[Pretty print]'
                    ;;
                osv-cache)
                    _arguments \\
                        '--stats[Show statistics]' \\
                        '--clear[Clear cache]' \\
                        '--dir[Cache directory]:directory:_files -/'
                    ;;
                init)
                    _arguments \\
                        '-f[Format]:format:(json js)' \\
                        '--format[Format]:format:(json js)' \\
                        '--force[Overwrite existing]'
                    ;;
                config)
                    _arguments \\
                        '-c[Config file]:file:_files' \\
                        '--config[Config file]:file:_files' \\
                        '--validate[Validate config]'
                    ;;
                pre-commit-config)
                    _arguments \\
                        '-o[Output file]:file:_files' \\
                        '--output[Output file]:file:_files'
                    ;;
                completions)
                    _arguments '1:shell:(bash zsh fish)'
                    ;;
                detect)
                    _arguments '1:directory:_files -/'
                    ;;
            esac
            ;;
    esac
}

_reachvet
`;
}

/**
 * Generate Fish completion script
 */
export function generateFishCompletions(): string {
  const cmdCompletions = COMMANDS.map(cmd =>
    `complete -c reachvet -n "__fish_use_subcommand" -a "${cmd}" -d "${COMMAND_DESCRIPTIONS[cmd] || ''}"`
  ).join('\n');

  const langCompletions = LANGUAGES.map(l =>
    `complete -c reachvet -n "__fish_seen_subcommand_from analyze check watch pre-commit" -l language -s l -xa "${l}"`
  ).join('\n');

  return `# Fish completion for reachvet
# Generated by ReachVet v${VERSION}
#
# Installation:
#   # Save to Fish completions directory:
#   reachvet completions fish > ~/.config/fish/completions/reachvet.fish
#
#   # Or system-wide:
#   reachvet completions fish | sudo tee /usr/share/fish/vendor_completions.d/reachvet.fish

# Disable file completions by default
complete -c reachvet -f

# Commands
${cmdCompletions}

# Languages (for --language option)
${langCompletions}

# analyze command options
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -s s -l source -d "Source directory" -r -a "(__fish_complete_directories)"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -s c -l components -d "Components JSON file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l sbom -d "SBOM file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l stdin -d "Read from stdin"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -s v -l verbose -d "Verbose output"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l pretty -d "Pretty print JSON"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l sarif -d "Output SARIF format"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l graph -d "Output Mermaid graph" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l dot -d "Output DOT graph" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l graph-direction -d "Graph direction" -xa "TB LR BT RL"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l vulnerable-only -d "Only vulnerable in graph"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l osv -d "Fetch from OSV.dev"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l osv-cache -d "OSV cache directory" -r -a "(__fish_complete_directories)"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l osv-ttl -d "OSV cache TTL seconds" -r
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l junit -d "Output JUnit XML" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l junit-all -d "Include all in JUnit"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l annotations -d "GitHub Actions annotations"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l annotations-notices -d "Include notices"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l sbom-cyclonedx -d "Output CycloneDX SBOM" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l sbom-spdx -d "Output SPDX SBOM" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l sbom-include-unreachable -d "Include unreachable"
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l vex -d "Output VEX statements" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l app-name -d "Application name" -r
complete -c reachvet -n "__fish_seen_subcommand_from analyze" -l app-version -d "Application version" -r

# check command options (same as analyze plus --json)
complete -c reachvet -n "__fish_seen_subcommand_from check" -s s -l source -d "Source directory" -r -a "(__fish_complete_directories)"
complete -c reachvet -n "__fish_seen_subcommand_from check" -s c -l components -d "Components JSON file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from check" -l sbom -d "SBOM file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from check" -l stdin -d "Read from stdin"
complete -c reachvet -n "__fish_seen_subcommand_from check" -l json -d "Output as JSON"
complete -c reachvet -n "__fish_seen_subcommand_from check" -l sarif -d "Output SARIF format"
complete -c reachvet -n "__fish_seen_subcommand_from check" -l osv -d "Fetch from OSV.dev"

# watch command options
complete -c reachvet -n "__fish_seen_subcommand_from watch" -s s -l source -d "Source directory" -r -a "(__fish_complete_directories)"
complete -c reachvet -n "__fish_seen_subcommand_from watch" -s c -l components -d "Components JSON file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from watch" -l sbom -d "SBOM file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from watch" -l osv -d "Fetch from OSV.dev"
complete -c reachvet -n "__fish_seen_subcommand_from watch" -l osv-cache -d "OSV cache directory" -r -a "(__fish_complete_directories)"
complete -c reachvet -n "__fish_seen_subcommand_from watch" -l osv-ttl -d "OSV cache TTL" -r
complete -c reachvet -n "__fish_seen_subcommand_from watch" -l debounce -d "Debounce milliseconds" -r
complete -c reachvet -n "__fish_seen_subcommand_from watch" -l quiet -d "Quiet mode"
complete -c reachvet -n "__fish_seen_subcommand_from watch" -l ignore -d "Ignore patterns" -r

# serve command options
complete -c reachvet -n "__fish_seen_subcommand_from serve" -s p -l port -d "Port number" -r
complete -c reachvet -n "__fish_seen_subcommand_from serve" -s H -l host -d "Host to bind" -r
complete -c reachvet -n "__fish_seen_subcommand_from serve" -l cors -d "Enable CORS"
complete -c reachvet -n "__fish_seen_subcommand_from serve" -l no-cors -d "Disable CORS"
complete -c reachvet -n "__fish_seen_subcommand_from serve" -l api-key -d "API key" -r
complete -c reachvet -n "__fish_seen_subcommand_from serve" -l rate-limit -d "Rate limit" -r
complete -c reachvet -n "__fish_seen_subcommand_from serve" -l no-rate-limit -d "Disable rate limit"
complete -c reachvet -n "__fish_seen_subcommand_from serve" -l osv-cache -d "Enable OSV cache"
complete -c reachvet -n "__fish_seen_subcommand_from serve" -l no-osv-cache -d "Disable OSV cache"
complete -c reachvet -n "__fish_seen_subcommand_from serve" -l cache-ttl -d "Cache TTL ms" -r

# pre-commit command options
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -s c -l components -d "Components JSON file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -l sbom -d "SBOM file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -l osv -d "Fetch from OSV.dev"
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -l osv-cache -d "OSV cache directory" -r -a "(__fish_complete_directories)"
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -l osv-ttl -d "OSV cache TTL" -r
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -l verbose -d "Verbose output"
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -l no-color -d "Disable colors"
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -l block-on-reachable -d "Block on any reachable"
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit" -l skip-no-staged -d "Skip if no staged files"

# pre-commit-config command options
complete -c reachvet -n "__fish_seen_subcommand_from pre-commit-config" -s o -l output -d "Output file" -r -F

# osv-lookup command options
complete -c reachvet -n "__fish_seen_subcommand_from osv-lookup" -s p -l package -d "Package name" -r
complete -c reachvet -n "__fish_seen_subcommand_from osv-lookup" -s v -l version -d "Package version" -r
complete -c reachvet -n "__fish_seen_subcommand_from osv-lookup" -s e -l ecosystem -d "Ecosystem" -xa "npm pypi go maven cargo crates.io nuget rubygems packagist"
complete -c reachvet -n "__fish_seen_subcommand_from osv-lookup" -l functions -d "Show functions only"
complete -c reachvet -n "__fish_seen_subcommand_from osv-lookup" -l pretty -d "Pretty print"

# osv-cache command options
complete -c reachvet -n "__fish_seen_subcommand_from osv-cache" -l stats -d "Show statistics"
complete -c reachvet -n "__fish_seen_subcommand_from osv-cache" -l clear -d "Clear cache"
complete -c reachvet -n "__fish_seen_subcommand_from osv-cache" -l dir -d "Cache directory" -r -a "(__fish_complete_directories)"

# init command options
complete -c reachvet -n "__fish_seen_subcommand_from init" -s f -l format -d "Config format" -xa "json js"
complete -c reachvet -n "__fish_seen_subcommand_from init" -l force -d "Overwrite existing"

# config command options
complete -c reachvet -n "__fish_seen_subcommand_from config" -s c -l config -d "Config file" -r -F
complete -c reachvet -n "__fish_seen_subcommand_from config" -l validate -d "Validate config"

# detect command - directory argument
complete -c reachvet -n "__fish_seen_subcommand_from detect" -a "(__fish_complete_directories)"

# completions command - shell type
complete -c reachvet -n "__fish_seen_subcommand_from completions" -xa "bash zsh fish"
`;
}

/**
 * Generate shell completions for the specified shell type
 */
export function generateCompletions(shell: ShellType): string {
  switch (shell) {
    case 'bash':
      return generateBashCompletions();
    case 'zsh':
      return generateZshCompletions();
    case 'fish':
      return generateFishCompletions();
    default:
      throw new Error(`Unsupported shell: ${shell}`);
  }
}

/**
 * Get list of supported shell types
 */
export function getSupportedShells(): ShellType[] {
  return ['bash', 'zsh', 'fish'];
}

/**
 * Get installation instructions for a shell type
 */
export function getInstallInstructions(shell: ShellType): string {
  switch (shell) {
    case 'bash':
      return `# Installation for Bash:

# For current session only:
source <(reachvet completions bash)

# Permanent (add to ~/.bashrc):
echo 'source <(reachvet completions bash)' >> ~/.bashrc

# Or save to system completions:
reachvet completions bash > /etc/bash_completion.d/reachvet

# For user completions (create directory if needed):
mkdir -p ~/.local/share/bash-completion/completions
reachvet completions bash > ~/.local/share/bash-completion/completions/reachvet`;

    case 'zsh':
      return `# Installation for Zsh:

# Create completions directory if needed:
mkdir -p ~/.zsh/completions

# Save completion script:
reachvet completions zsh > ~/.zsh/completions/_reachvet

# Add to fpath in ~/.zshrc (if not already):
# fpath=(~/.zsh/completions $fpath)

# Rebuild completions:
rm -f ~/.zcompdump; compinit

# Or for Oh My Zsh users:
reachvet completions zsh > ~/.oh-my-zsh/completions/_reachvet`;

    case 'fish':
      return `# Installation for Fish:

# Save to Fish completions directory:
reachvet completions fish > ~/.config/fish/completions/reachvet.fish

# Or system-wide:
reachvet completions fish | sudo tee /usr/share/fish/vendor_completions.d/reachvet.fish

# Completions are loaded automatically in Fish.`;

    default:
      return `Unknown shell: ${shell}`;
  }
}
